spring.application.name=ReviewSvc
server.port=9090

spring.datasource.url=jdbc:mysql://localhost:3306/reviewsvc?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=weed3011

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true

spring.cache.type=simple
spring.datasource.hikari.initializationFailTimeout=0
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


